name: generator

on:
  issues:
    types:
      - closed
      - deleted
      - edited
      - labeled
      - opened
      - pinned
      - reopened
      - transferred
      - unlabeled
      - unpinned

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node_version: [18.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generate blog post
        uses: Deuscx/issue-blog-action@v0.0.5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          output: content/posts
